# Defines the Filter Status subfields for the Spatial INS System State messagesuint8 orientation_filter_initialised
#
uint8 ins_filter_initialised
uint8 heading_initialised
uint8 utc_time_initialised
uint8 gnss_fix_type
uint8 event1_flag
uint8 event2_flag
uint8 internal_gnss_enabled
uint8 magnetic_heading_enabled
uint8 velocity_heading_enabled
uint8 atmospheric_altitude_enabled
uint8 external_position_active
uint8 external_velocity_active
uint8 external_heading_active