# Defines the System Status subfields for the Spatial INS System State messages
#
uint8 system_failure
uint8 accelerometer_sensor_failure
uint8 gyroscope_sensor_failure
uint8 magnetometer_sensor_failure
uint8 pressure_sensor_failure
uint8 gnss_failure
uint8 accelerometer_over_range
uint8 gyroscope_over_range
uint8 magnetometer_over_range
uint8 pressure_over_range
uint8 minimum_temperature_alarm
uint8 maximum_temperature_alarm
uint8 low_voltage_alarm
uint8 high_voltage_alarm
uint8 gnss_antenna_disconnected
uint8 serial_port_overflow_alarm