(cl:in-package pamplemousse_sensors-msg)
(cl:export '(INS_FILTER_INITIALISED-VAL
          INS_FILTER_INITIALISED
          HEADING_INITIALISED-VAL
          HEADING_INITIALISED
          UTC_TIME_INITIALISED-VAL
          UTC_TIME_INITIALISED
          GNSS_FIX_TYPE-VAL
          GNSS_FIX_TYPE
          EVENT1_FLAG-VAL
          EVENT1_FLAG
          EVENT2_FLAG-VAL
          EVENT2_FLAG
          INTERNAL_GNSS_ENABLED-VAL
          INTERNAL_GNSS_ENABLED
          MAGNETIC_HEADING_ENABLED-VAL
          MAGNETIC_HEADING_ENABLED
          VELOCITY_HEADING_ENABLED-VAL
          VELOCITY_HEADING_ENABLED
          ATMOSPHERIC_ALTITUDE_ENABLED-VAL
          ATMOSPHERIC_ALTITUDE_ENABLED
          EXTERNAL_POSITION_ACTIVE-VAL
          EXTERNAL_POSITION_ACTIVE
          EXTERNAL_VELOCITY_ACTIVE-VAL
          EXTERNAL_VELOCITY_ACTIVE
          EXTERNAL_HEADING_ACTIVE-VAL
          EXTERNAL_HEADING_ACTIVE
))