(cl:in-package pamplemousse_sensors-msg)
(cl:export '(HEADER-VAL
          HEADER
          SYSTEM_STATUS-VAL
          SYSTEM_STATUS
          FILTER_STATUS-VAL
          FILTER_STATUS
          UNIX_TIME_SECONDS-VAL
          UNIX_TIME_SECONDS
          MICROSECONDS-VAL
          MICROSECONDS
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          VELOCITY-VAL
          VELOCITY
          BODY_ACCELERATION-VAL
          BODY_ACCELERATION
          G_FORCE-VAL
          G_FORCE
          ORIENTATION-VAL
          ORIENTATION
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          STANDARD_DEVIATION-VAL
          STANDARD_DEVIATION
))