// Generated by gencpp from file pamplemousse_actuators/wingActuatorStates.msg
// DO NOT EDIT!


#ifndef PAMPLEMOUSSE_ACTUATORS_MESSAGE_WINGACTUATORSTATES_H
#define PAMPLEMOUSSE_ACTUATORS_MESSAGE_WINGACTUATORSTATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pamplemousse_actuators
{
template <class ContainerAllocator>
struct wingActuatorStates_
{
  typedef wingActuatorStates_<ContainerAllocator> Type;

  wingActuatorStates_()
    : header()
    , operating_mode(0)
    , statusword(0)
    , actual_position(0)  {
    }
  wingActuatorStates_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , operating_mode(0)
    , statusword(0)
    , actual_position(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _operating_mode_type;
  _operating_mode_type operating_mode;

   typedef uint16_t _statusword_type;
  _statusword_type statusword;

   typedef int32_t _actual_position_type;
  _actual_position_type actual_position;





  typedef boost::shared_ptr< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> const> ConstPtr;

}; // struct wingActuatorStates_

typedef ::pamplemousse_actuators::wingActuatorStates_<std::allocator<void> > wingActuatorStates;

typedef boost::shared_ptr< ::pamplemousse_actuators::wingActuatorStates > wingActuatorStatesPtr;
typedef boost::shared_ptr< ::pamplemousse_actuators::wingActuatorStates const> wingActuatorStatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator1> & lhs, const ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.operating_mode == rhs.operating_mode &&
    lhs.statusword == rhs.statusword &&
    lhs.actual_position == rhs.actual_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator1> & lhs, const ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pamplemousse_actuators

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f35dfd3ce2f32fc079e116f9467f3493";
  }

  static const char* value(const ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf35dfd3ce2f32fc0ULL;
  static const uint64_t static_value2 = 0x79e116f9467f3493ULL;
};

template<class ContainerAllocator>
struct DataType< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pamplemousse_actuators/wingActuatorStates";
  }

  static const char* value(const ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# wingActuatorStates.msg\n"
"# This is a message to hold the state messages for an individual Nanotec Actuator\n"
"#\n"
"# The state is exactly the Statusword (6041h)\n"
"Header header\n"
"\n"
"# 6060h Modes of Operation\n"
"# The desired operating mode is entered in this object.\n"
"int8 operating_mode\n"
"\n"
"# 6041h Statusword\n"
"# This object returns information about the status of the CiA 402 Power State Machine\n"
"uint16 statusword\n"
"\n"
"# 6063h Position Actual Internal Value\n"
"# Contains the current rotary encoder position in increments\n"
"int32 actual_position \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.operating_mode);
      stream.next(m.statusword);
      stream.next(m.actual_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wingActuatorStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pamplemousse_actuators::wingActuatorStates_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "operating_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.operating_mode);
    s << indent << "statusword: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.statusword);
    s << indent << "actual_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.actual_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAMPLEMOUSSE_ACTUATORS_MESSAGE_WINGACTUATORSTATES_H
